### ISSUE TITLE
PCB components miss match with The Screen

### ISSUE THREAD

**Issue by hiro-v2** [Tokibot1/ECE-411-Group-10#1]
In the PCB circuit, the OLED screen has different pinout orders as the component we have. There are a lot of similar of this kind of screens out on the Market, they look the same but some have different VCC and GND pin orders. We have a mismatch on that so the first one on our PCB burns out! I've already bought some new pieces that matches !

**Comment by hirovel** [comment]
We need to test the new screen first as it has a different address

**Comment by hirovel** [comment]
Remember although the backside of the screen writes address 0x78, the real address is 0x3C
